site:
  title: Sparrow Docs
  start_page: sprw::index.adoc
content:
  sources:
    - url: ./..
      start_path: Docs
output:
  clean: true
  dir: ../public
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
urls:
  html_extension_style: indexify
antora:
  extensions:
    - require: '@antora/pdf-extension'
